fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations

  versioning:
    enabled: true
    resolvers:
      media_type: # Accept header
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'

  param_fetcher_listener: true

  view:
    view_response_listener: true
    mime_types:
      json:
        [ "application/json", "application/json;version=1.0", "application/json;version=2.0"]

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

  
